language: generic

sudo: required


before_install:
  - git config --global user.name "$USERNAME" 
  - git config --global user.email "$EMAIL"

script:
  - chmod +x tools/auto-update.sh
  - chmod +x tools/deploy.sh
  - tools/auto-update.sh