name: Auto Update
on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - master
  pull_request: []

env:
  EMAIL: zhengjunyi@live.com
  GH_REF: github.com/Mogeko/homebrew-taps.git
  GH_WIKI: github.com/Mogeko/homebrew-taps.wiki.git
  DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
  USERNAME: Mogeko

jobs:
  auto-update:
    runs-on: ubuntu-latest
    container:
      image: alpine/git
    steps:
    - name: Setup Script
      run: |
        chmod +x .github/workflows/auto-update.sh
        chmod +x .github/workflows/checker.sh
        chmod +x .github/workflows/update.repo.sh
        chmod +x .github/workflows/update.wiki.sh
    - name: Setup git
      run: |
        git config --global user.name "$USERNAME" 
        git config --global user.email "$EMAIL"
    - name: Run Script
      run: |
        .github/workflows/auto-update.sh
        .github/workflows/checker.sh
        .github/workflows/update.repo.sh
        .github/workflows/update.wiki.sh
